---
colorize: true
style: monokai
formatter: terminal16m
cheatpaths:
  - name: community
    path: /usr/share/cheat/cheatsheets/community
    tags: [ community ]
    readonly: true
  - name: personal
    path: ~/.config/cheat/cheatsheets/personal
    tags: [ personal ]
    readonly: false
