
[[Snippets]]
  Description = "List available forms"
  Output = ""
  Tag = []
  command = "fc-list"

[[Snippets]]
  Description = "NCurses Disk Usage - Disk usage analyzer"
  Output = ""
  Tag = []
  command = "ncdu"

[[Snippets]]
  Description = "Friendly and fast tool for sending HTTP requests"
  Output = ""
  Tag = []
  command = "xh"
